# Libera conexões MQTT padrão (ESP32 e Servidor Node)
listener 1883 0.0.0.0
allow_anonymous true

# Libera o protocolo WebSockets (Interface Web)
listener 8080 0.0.0.0
protocol websockets
allow_anonymous true